# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_API: ROLE_API

    providers:
        chain_provider:
            chain:
                providers: [api_provider]

        api_provider:
            memory_api:
                users:
                    micro_service_asset:
                        password: '%env(GITLAB_BOT_TOKEN)%'
                        roles: 'ROLE_API'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

        webhooks_secured:
            pattern: ^/webhooks/*
            stateless: true
            simple_preauth:
                authenticator: oslab_security_api.security.authentication.authenticator
            provider: api_provider
